---
- name: "Установка apache2 и настройка титульной страницы"
  hosts: webservers
  become: true

  vars:
    server_name: "{{ ansible_fqdn }}"
    server_ip: "{{ ansible_all_ipv4_addresses[1] }}"
    server_os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"

  tasks:
    - name: "Установка сервера apache2"
      apt:
        name: apache2
        state: present

    - name: "Перенос файла index.html"
      template:
       src: templates/index.html.j2
       dest: /var/www/html/index.html
       mode: '0644'

    - name: "Запуск apache2 в текущей сессии"
      service:
        name: apache2
        state: started
        enabled: false

    - name: "Добавление  apache2 в автозагрузку"
      systemd:
        name: apache2
        enabled: true
        masked: false

    - name: "Добавляем порт 80 в ufw"
      ufw:
        rule: allow
        port: '80'
        comment: "открываем порт 80"

    - name: "Проверяем доступность сайта"
      uri:
        url: http://{{ server_ip }}
        return_content: no
        status_code: 200
      register: site_response

    - name: "Доступен ли сайт?"
      debug:
        msg: "Сайт доступен: {{ site_response.status == 200 }}"
        
    - name: "Вывод адреса веб-страницы apache2"
      debug:
        msg: "Откройте веб-браузер и перейдите по адресу http://{{ server_ip }}/"

...